import { StyleSheet } from "react-native";
import colors from "@assets/styles/colors";

const styles = StyleSheet.create({
  content: {
    width: "100%",
    height: "100%",
    display: "flex",
    flexDirection: "column",
  },
  cardImage: {
    zIndex: 1,
    width: "100%",
    height: "40%",
    display: "flex",
    flexDirection: "column",
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: colors.secondary,
  },
  contentInfo: {
    zIndex: 2,
    top: -30,
    height: "100%",
    width: "100%",
    borderTopLeftRadius: 35,
    borderTopRightRadius: 35,
    backgroundColor: colors.light,
    paddingHorizontal: 25,
    paddingVertical: 25,
  },
  contentTitle: {
    width: "100%",
    display: "flex",
    flexDirection: "row",
    justifyContent: "space-between",
  },
  contentBreed: {
    top: -48,
    height: 45,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: colors.primary,
    paddingHorizontal: 15,
    marginRight: 20,
    borderRadius: 10,
  },
  breedText: {
    color: colors.light,
    fontSize: 20,
    fontWeight: "bold",
  },
  title: {
    fontSize: 28,
    color: colors.dark,
    fontWeight: "bold",
  },
  subTitle: {
    fontSize: 15,
    color: colors.gray,
  },
  info: {
    display: "flex",
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    height: 120,
  },
  cardInfo: ({ color }) => ({
    display: "flex",
    justifyContent: "space-between",
    fontSize: 15,
    height: 80,
    width: 80,
    alignItems: "center",
    borderRadius: 10,
    backgroundColor: color + "aa",
  }),
  topCardInfo: {
    height: 50,
    width: 80,
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    paddingHorizontal: 5,
  },
  topText: {
    color: colors.light,
    fontSize: 15,
  },
  bottomCardInfo: ({ color }) => ({
    height: 30,
    width: 80,
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: color,
    borderRadius: 10,
  }),
});
export default styles;
